### PR TITLE
Add two fallback boot pathways for UEFI

### LINKED ISSUE #7542: Fall back to UEFI shell if Qubes boot entry is missing
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Latest as of posting, 4.1.0

### Brief summary

I manually unplugged every drive on my computer except for the target drive for the installation, which was all free space unpartitioned. Installer ran typically, chose automatic for the installation type. Booted into the OS' configuration and then the full OS.

GRUB is verified to have worked because I managed to see it when initially booting for configuration and because of a later restart due to a display artificating and then system lockup problem I had that I attribute to Nvidia. 

After using another drive and then unplugging it, and plugging the Qubes drive back, there was no detectable boot source. 

I booted a live OS and found that the partition structure was intact but didn't investigate further and reinstalled Qubes. 

I then got the idea to see if this issue happened if I BIOS disabled drives instead of unplugging them. I disabled my Qubes drive and enabled another, and booted into it fine. I then disabled my other drive and reenabled the Qubes drive and the same issue happened again where my system does not see any boot entries. 

The system does see the drive, and switching on CSM and legacy boot I can boot from the drive but get an error screen saying to boot from proper media. 
 

This second time, I _kind of_ fixed it but I must do these steps every time I remove the drive or disable it in BIOS. I lose the option to boot without the Xen hypervisor and the boot hiccups. I essentially have to boot my install media, run Anaconda rescue and:

1. Mount the bootloader partition
2. Copy the contents of /mnt/EFI/qubes/ to /mnt/EFI/BOOT/
3. Rename grubx64.efi to bootx64.efi
4. Rename grub.cfg to bootx64.cfg
5. efibootmgr -v -c -u -L Qubes2 -l /EFI/BOOT/bootx64.efi -d /dev/sda -p 1

### Steps to reproduce

I believe the best way to reproduce this issue is to do a fresh install of Qubes on hardware similar to mine: 

Asus Prime Z-390-A Motherboard
Intel i7-9700K CPU
16GB DDR4 RAM
1TB HDD

Most notably, this motherboard. I will be filing a compatibility report soon, but I believe this motherboard may have something to do with how it reads the GRUB bootloader as it's configured for Qubes. 

Further, these are the only non-stock BIOS settings:

- Disabling the Intel LAN Controller (it causes a PCI reset error and ends the last step of the configuration, doesn't matter since I don't use it, and I believe the fact that it's unplugged is the reason this issue happens)
- Enabling Virtualization
- Enabling Vt-d
- Disabling all other drives 

### Expected behavior

The GRUB bootloader is supposed to appear after the BIOS initializes regardless of whether the drive was previously unplugged from the system or not (safely of course). 

### Actual behavior

Please read above. 

After unplugging the drive or disabling it in BIOS, the entry for GRUB is missing.

### LINKED ISSUE #8363: Raw disk backup of Qubes EFI is unbootable
### Qubes OS release

R4.1 and R4.2

### Brief summary

When making a raw disk backup from a Qubes installed to an internal hard drive to an external hard drive, the external hard drive is unbootable.

raw disk backup means a backup using `dd` or 1 to 1 exact copy.

### Steps to reproduce

1. install Qubes normally on a computer that only support EFI booting on the internal harddrive
2. reboot
3. brief test that Qubes is working normally (yes)
4. shutdown Qubes
5. boot from an external drive, boot a live DVD or live USB such as Debian Live
6. perform a raw disk backup from the internal disk to the external disk
7. unplug that disk and try to boot from it in a different computer (or the same Qubes computer)

([example instructions for raw disk backups](https://www.kicksecure.com/wiki/Raw_Disk_Backup))

### Expected behavior

The raw disk backup of Qubes is bootable.

### Actual behavior

The raw disk backup of Qubes is unbootable.

### Additional information

According to my research that might be because of missing entries in the EFI firmware's NVRAM which is stored on the motherboard. Unfortunately, the EFI boot process doesn't seem by default to be self-contained on 1 harddrive but require extra settings stored outside harddrives on the motherboard (EFI NVRAM).

Using `grub2-install` with options `--removable` / `--force-extra-removable` during Qubes installation might help?

> [--removable](https://manpages.debian.org/bookworm/grub2-common/grub-install.8.en.html#removable)
> the installation device is removable. This option is only available on EFI.

> [--force-extra-removable](https://manpages.debian.org/bookworm/grub2-common/grub-install.8.en.html#force~2)
> force installation to the removable media path also. This option is only available on EFI.

Qubes does not have good support for multiboot support anyhow:

* https://github.com/QubesOS/qubes-issues/issues/8351
* https://www.qubes-os.org/faq/#can-i-install-qubes-os-together-with-other-operating-system-dual-bootmulti-boot
* It's "patches welcome". (And that's okay.)

This ticket is not a feature request to improve multiboot support. Why do I mention this? Because otherwise, when considering options `--removable` / `--force-extra-removable` one *might* argue "but that breaks mutliboot support". I would argue that being able to boot a raw disk backup of Qubes is more important than mutliboot support.

[Why do I like full raw disk backups? See this link.](https://forum.qubes-os.org/t/how-do-you-organize-your-backups/3986/16?u=adrelanos)

Manually updating the NVRAM can be challenging:

* It's vendor dependent because of many different EFI BIOS versions.
* Some BIOS don't even have such an option.
* Might require booting into an operating system installed on USB and running console commands to fix it.
* Difficult, impossible for far most users to do or even to find instructions for it.

Qubes with legacy BIOS booting as far as I remember didn't have this issue. However, never notebooks sometimes (or often, dunno) don't even support legacy BIOS booting anymore. Therefore "use legacy BIOS booting" is a non-solution. Also not a good long term solution in either case because of Qubes planned Secure Boot support.

This bug might also make Qubes "non-portable". Meaning, Qubes installed to an external drive such as a USB SSD might be bootable on the computer where it was installed but unbootable when attempting to boot the same Qubes USB SSD on another computer. I didn't test this very part mentioned in this very chapter. Anaconda by Fedora might be using `grub2-install` with options `--removable` / `--force-extra-removable` already when installing to external devices (USB) instead of internal harddrive.

Where is the Qubes code which defines bootloader / grub2 / EFI installation? Or is this currently all done by upstream's Anaconda?

### PR DESCRIPTION
**Pull request by rustybird**
Fixes QubesOS/qubes-issues#7542
Fixes QubesOS/qubes-issues#8363

### CODE REVIEW

**Comment by marmarek** [comment]
See also #15

**Comment by marmarek** [comment]
Can you split this into two commits or even two PRs? Adding `startup.nsh` is IMO low risk change, but BOOTx64.EFI might conflict with something else there (if there is multiboot for example) or change how UEFI enumerate boot entries on the disk (I wouldn't be surprised if there is some buggy UEFI implementation which would ignore other configured entries if it finds `BOOTx64.EFI` first).

**Comment by rustybird** [comment]
Sure, here it is as two commits. The `startup.nsh` commit is first, so you can merge just that one and leave the rest of the PR open if you like.

> BOOTx64.EFI might conflict with something else there (if there is multiboot for example) 

It wouldn't be overwritten, see the second commit message.

> I wouldn't be surprised if there is some buggy UEFI implementation which would ignore other configured entries if it finds `BOOTx64.EFI` first

If that's something that happens, I guess it might annoy people who want to continue booting some other OS by default (and that other OS or anything else didn't already install an EFI file at the default image location).

**Comment by rustybird** [comment]
ping @marmarek, in case this is something that you want in the R4.2.1 installer

QubesOS/qubes-issues#8935

**Review by marmarek — APPROVED** [review]

**Comment by marmarek** [comment]
https://github.com/QubesOS/qubes-lorax-templates/commit/e1cc6584a907ed37235b23ca0a51b9e41a22c7a2 :(

**Pull request merged**
