### PR TITLE
Update to grub 2.06

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by fepitre** [comment]
If needed, we can shortcut patches list.

**Comment by marmarek** [comment]
> If needed, we can shortcut patches list.

Yes, definitely. A bunch of them are outright harmful, like the re-enabling os-prober (and a comment: "Disable os-prober by default due to security reasons."), or bls (bootloader specification) thing (that is incompatible with Xen and only introduces some mess). There used to be a patch removing/disabling multiboot2 module on EFI (to avoid interactions with Secure Boot) which breaks Xen - but I don't see such patch anymore. Anyway, it will require testing on EFI too.
The patch 152 looks risky, although I think it doesn't matter _now_ since we don't use TPM support in grub (so, better keep it to improve reliability).
I don't like 169 too.

As for `grub.spec`, I pasted the whole `grub.macros` directly into `grub.spec` to avoid issues with include. But if it works now (for both legacy and mock builds), I think we can keep it.

**Comment by fepitre** [comment]
PipelineRetry

**Comment by marmarek** [comment]
closing in favor of #11 (which includes parts of this PR too)

**Pull request closed without merging**
